defaultPlacement: end
enableVersioning: true
handle: about
name: About
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bc661644-8fb6-4894-92fb-ba1b7b4be651: # craft-cms
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: about
type: single
